### ISSUE TITLE
ssl.PROTOCOL_TLSv1 problems

### ISSUE THREAD

**Issue by btb** [uw-it-aca/uw-restclients-core#44]
While testing uw_restclients_r25 with the 25Live web service, I'm now getting the error "[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)"
I don't believe I changed anything on my end since it was last working, so I think this means they just updated their servers to reject TLSv1, which restclients_core.dao has hard-coded. If I change it to ssl.PROTOCOL_TLSv1_2, it works again. Should this be added as a service-specific setting or is there something else I'm missing?

**Comment by jlaney** [comment]
I'm thinking it should be a per-service setting.  The app settings will be TLS_VERSION, and a django app settings.py should look like:

import ssl
RESTCLIENTS_r25_TLS_VERSION = ssl.PROTOCOL_TLSv1_2

**Comment by jlaney** [comment]
Added in 0.9.5.
