### ISSUE TITLE
__del__ on models is causing too many errors

### ISSUE THREAD

**Issue by jlaney** [uw-it-aca/uw-restclients-core#8]
Our error logs are now filled with messages like this:

[Tue Mar 28 13:49:42 2017] [error] Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method CanvasUser.\_\_del\_\_ of <restclients.models.canvas.CanvasUser object at 0x7fca8c307510>> ignored
[Tue Mar 28 13:49:42 2017] [error] Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method CanvasEnrollment.\_\_del\_\_ of <restclients.models.canvas.CanvasEnrollment object at 0x7fca8c3077d0>> ignored
[Tue Mar 28 13:49:42 2017] [error] Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method CanvasUser.\_\_del\_\_ of <restclients.models.canvas.CanvasUser object at 0x7fca8c307590>> ignored
[Tue Mar 28 13:49:42 2017] [error] Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method CanvasEnrollment.\_\_del\_\_ of <restclients.models.canvas.CanvasEnrollment object at 0x7fca8749c450>> ignored
[Tue Mar 28 13:49:42 2017] [error] Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method CanvasUser.\_\_del\_\_ of <restclients.models.canvas.CanvasUser object at 0x7fca8749ccd0>> ignored

**Comment by vegitron** [comment]
Resolved in release 0.8.4
